In [81]:
import numpy as np

In [82]:
arr = np.array(42)
print(arr)

42


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
a = np.array(42)
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
2
3


In [29]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)

[[[[[1 2 3 4]]]]]


In [31]:
arr = np.array(["Prayoos", "Prawish", "Prasars"])
print(arr[0])

Prayoos


In [37]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("5th element on 2nd dim: ", arr[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd dim:  10


In [38]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1,-1])

Last element from 2nd dim:  10


In [49]:
arr = np.array([1,2,3,4,5,6,7])
slice_arr = arr[1:5]
print(arr)
print(slice_arr)

[1 2 3 4 5 6 7]
[2 3 4 5]


In [50]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [65]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)
newarr2 = arr.reshape(2,3,2)
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [69]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [76]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)
